receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        # Uncomment to enable TLS
        # tls:
        #   cert_file: /etc/otelcol/ca/otelcol.crt
        #   key_file: /etc/otelcol/ca/otelcol.key
        # auth:
        #   authenticator: bearerauth
processors:
  resource:
    attributes:
    - action: insert
      key: loki.resource.labels
      value: sampler_name

exporters:
  logging:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

extensions:
  health_check:
    endpoint: 0.0.0.0:8000
  neblic:
    endpoint: 0.0.0.0:8899
    storage_path: /var/lib/otelcol/
  # Uncomment to enable TLS
  #   tls:
  #     cert_file: /etc/otelcol/ca/otelcol.crt
  #     key_file: /etc/otelcol/ca/otelcol.key
  #   auth:
  #     type: bearer
  #     bearer:
  #       token: some_secret_token

  # Data plane bearer authentication
  # bearerauth:
  #   token: some_secret_token

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    logs:
      receivers:
      - otlp
      processors:
      - resource
      exporters:
      - logging
      - loki
  extensions: [neblic, health_check]